package org.drools.test;

/*
import mock.MockFact;
import org.drools.fipa.body.content.Action;
import org.drools.informer.*;
import org.drools.informer.surveyAgent.*;



rule "Call Interface"
when
    $p : MockFact( $a : age )
then
    System.out.println(" SESSION #2 >>> Invoking local service " );
    double $x = Math.sqrt($a);
    insert( new Double($x*$x) );
end




declare LocalTrigger
    x : int
end

rule "Call rules"
when
    $p : MockFact( $a : age )
then
    System.out.println(" SESSION #2 >>> Invoking rule-based service " );
    insert( new LocalTrigger($a) );
end


rule "Rule Op"
when
    LocalTrigger( $x : x )
then
    insert( new Integer($x*$x) );
end





rule "Action_Request : getSurvey"
when
    $a : Action( actionName == "getSurvey",
                 $surveyClass : args["surveyClass"],
                 $userId : args["userId"],
                 $surveyId : args["surveyId"],
                 $context : args["context"],
                 $lang : args["language"] )
    not SurveyTicket( sid == $surveyId )

then
//    System.err.println("NEEDED SURVEY " + $surveyClass  +" " + ((String) $surveyId) +" " + ((String) $userId) +" " + ((String) $context) );
    insert( new SurveyTicket( (String) $surveyId, (String) $surveyClass, (String) $userId, (String) $context, (String) $lang, null) );
end


query getSurvey( String $sid )
    $return : SurveyGUIAdapter( surveyId == $sid )
end



//rule "Log"
//when
//    $o : Object()
//then
//    System.out.println("SESSION #2 >>> " + $o);
//end
*/
