
package org.drools.dssagentserver;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SynchronousDroolsAgentServiceImplService", targetNamespace = "http://dssagentserver.drools.org/", wsdlLocation = "http://localhost:9944/clinical-decision-support-agent/service/SynchronousDroolsAgentService?wsdl")
public class SynchronousDroolsAgentServiceImplService
    extends Service
{

   // private final static URL SYNCHRONOUSDROOLSAGENTSERVICEIMPLSERVICE_WSDL_LOCATION = null;
    private final static Logger logger = Logger.getLogger(org.drools.dssagentserver.SynchronousDroolsAgentServiceImplService.class.getName());

//    static {
//        URL url = null;
//        try {
//            URL baseUrl;
//            baseUrl = org.drools.dssagentserver.SynchronousDroolsAgentServiceImplService.class.getResource(".");
//            url = new URL(baseUrl, "http://localhost:9944/clinical-decision-support-agent/service/SynchronousDroolsAgentService?wsdl");
//        } catch (MalformedURLException e) {
//            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9944/clinical-decision-support-agent/service/SynchronousDroolsAgentService?wsdl', retrying as a local file");
//            logger.warning(e.getMessage());
//        }
//        SYNCHRONOUSDROOLSAGENTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
//    }

    public SynchronousDroolsAgentServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SynchronousDroolsAgentServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, new QName("http://dssagentserver.drools.org/", "SynchronousDroolsAgentServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns SynchronousDroolsAgentServiceImpl
     */
    @WebEndpoint(name = "SynchronousDroolsAgentServiceImplPort")
    public SynchronousDroolsAgentServiceImpl getSynchronousDroolsAgentServiceImplPort() {
        return super.getPort(new QName("http://dssagentserver.drools.org/", "SynchronousDroolsAgentServiceImplPort"), SynchronousDroolsAgentServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SynchronousDroolsAgentServiceImpl
     */
    @WebEndpoint(name = "SynchronousDroolsAgentServiceImplPort")
    public SynchronousDroolsAgentServiceImpl getSynchronousDroolsAgentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dssagentserver.drools.org/", "SynchronousDroolsAgentServiceImplPort"), SynchronousDroolsAgentServiceImpl.class, features);
    }

}
