/*
    Message content processing.
    Determines the actions necessary to handle a message
    The actions will be executed on a target session, as decided by the routing rules
*/

package org.drools.fipa;

import org.drools.runtime.StatefulKnowledgeSession;
import org.drools.fipa.ACLMessage;
import org.drools.command.CommandFactory;
import org.drools.command.BatchExecutionCommand;
import org.drools.runtime.rule.QueryResults;

import org.drools.fipa.body.content.*;
import org.drools.fipa.body.acts.*;
import org.drools.fipa.MessageContentHelper;
import org.drools.fipa.MessageContentFactory;

import java.util.List;
import java.util.ArrayList;




/*
rule "Decode"
salience 9999
no-loop
when
    $msg : ACLMessage( $msgId : id, $body : body  )
then
    System.err.println("Decoding " + $msgId);
    $body.decode($msg.getEncoding());
    update($msg);
end
*/


rule "Invoke"
when
    $msg : ACLMessage( $msgId : id )
    $dst : Destination( $msgId , $sessionId ; )
    $cmd : MessageCommands( $msgId, $batch ; )
then
    System.err.println("EXECUTING msg commands for "+ $msgId + " in " + $sessionId);
    System.err.println("\t commands " + $cmd);

    retract($dst);
    retract($cmd);
    StatefulKnowledgeSession kSession = (StatefulKnowledgeSession) proxies.get($sessionId);
    
    org.drools.runtime.impl.ExecutionResultImpl result = (org.drools.runtime.impl.ExecutionResultImpl) kSession.execute($batch);

    insert( new ResponseContent($msgId, result.getValue("$out_"+$msgId)) );
end


rule "Invoke_OneShot"
salience 1
when
    $msg : ACLMessage( $msgId : id )
    $dst : Destination( $msgId , $sessionId ; )
    $cmd : OneShotMessageCommand( $msgId, $act ; )
then
    System.err.println("EXECUTING msg command ONE for "+ $msgId + " in " + $sessionId);
    retract($cmd);
    StatefulKnowledgeSession kSession = (StatefulKnowledgeSession) proxies.get($sessionId);

    kSession.execute($act);
    kSession.execute(CommandFactory.newFireAllRules());
end







rule "Process_Inform"
when
    $msg : ACLMessage( $msgId : id, performative == Act.INFORM )
    Inform( $info : proposition ) from $msg.body
    $dst : Destination( $msgId ; )
then
    System.err.println(" INTERNAL PROCESSING : GENERATING COMMANDS FOR INFORM " + $msgId );

    List list = new ArrayList(2);
            list.add(CommandFactory.newInsert( $info.getData(), "$out_"+$msgId ));
            list.add(CommandFactory.newFireAllRules());
    BatchExecutionCommand batch = CommandFactory.newBatchExecution(list);
    insert( new MessageCommands( $msgId, batch ) );
end





rule "Process_QueryIf"
when
    $msg : ACLMessage( $msgId : id, performative == Act.QUERY_IF )
    QueryIf( $info : proposition ) from $msg.body
    $dst : Destination( $msgId ; )
then
    System.err.println(" INTERNAL PROCESSING : GENERATING COMMANDS FOR QUERYIF " + $msgId );

    List list = new ArrayList(1);
            list.add(CommandFactory.newQuery( "$out_"+$msgId, "queryIf", new Object[] {$info.getData()} ));
    BatchExecutionCommand batch = CommandFactory.newBatchExecution(list);
    insert( new MessageCommands( $msgId, batch ) );
end


rule "Fix_QueryIf_Results"
salience 9999
no-loop
when
    $msg : ACLMessage( $msgId : id, performative == Act.QUERY_IF )
    $cont : ResponseContent( messageId == $msgId, $data : data )
then
    $cont.setData(((QueryResults) $data).iterator().next().get("$queryIf"));
    update($cont);
end






rule "Process_QueryRef"
when
    $msg : ACLMessage( $msgId : id, performative == Act.QUERY_REF )
    QueryRef( $query : query ) from $msg.body
    $dst : Destination( $msgId ; )
then
    System.err.println(" INTERNAL PROCESSING : GENERATING COMMANDS FOR QUERYREF " + $msgId );

    List list = new ArrayList(2);
            list.add(CommandFactory.newQuery( "$out_"+$msgId, $query.getQueryName() , $query.getArgs().toArray() ));
    BatchExecutionCommand batch = CommandFactory.newBatchExecution(list);
    insert( new MessageCommands( $msgId, batch ) );
end


rule "Fix_QueryRef_Results"
salience 9999
no-loop
when
    $msg : ACLMessage( $msgId : id, performative == Act.QUERY_REF )
    QueryRef( $query : query ) from $msg.body
    $cont : ResponseContent( messageId == $msgId, $data : data )
then
    $cont.setData(MessageContentHelper.getQueryReferences($query, (QueryResults) $data));
    update($cont);
end












rule "Process_Request"
when
    $msg : ACLMessage( $msgId : id, performative == Act.REQUEST )
    $req : Request( $act : action, $actName : action.actionName ) from $msg.body
    $dst : Destination( $msgId ; )
then
    System.err.println(" INTERNAL PROCESSING : GENERATING COMMANDS FOR REQUEST " + $msgId );

    List list = new ArrayList(3);
            list.add(CommandFactory.newInsert( $act ));
            list.add(CommandFactory.newFireAllRules());
            
            list.add(CommandFactory.newQuery( "$out_"+$msgId, $act.getActionName() , MessageContentHelper.getActionArgsArray($act)) );
    BatchExecutionCommand batch = CommandFactory.newBatchExecution(list);
    insert( new MessageCommands( $msgId, batch ) );
end


rule "Fix_Request_Results"
salience 9999
no-loop
when
    $msg : ACLMessage( $msgId : id, performative == Act.REQUEST )
    $req : Request( $act : action, $actName : action.actionName ) from $msg.body
    $cont : ResponseContent( messageId == $msgId, $data : data )
then
    
   $cont.setData( MessageContentHelper.getActionReferences($act, (QueryResults) $data));
    update($cont);
end






rule "Process_Request_When"
when
    $msg : ACLMessage( $msgId : id, performative == Act.REQUEST_WHEN )
    $req : RequestWhen( $act : action, $actName : action.actionName, $condition : condition.drl ) from $msg.body
    $dst : Destination( $msgId ; )
then
    System.err.println(" INTERNAL PROCESSING : GENERATING COMMANDS FOR REQUEST WHEN " + $msgId + " " + $condition);
    ActionHolder holder = new ActionHolder($msgId, $act, $condition, false);

    insert( new OneShotMessageCommand( $msgId,  CommandFactory.newInsert( holder ) ) );

    java.util.List list = new ArrayList(1);
              list.add(CommandFactory.newFireAllRules());
//            list.add(CommandFactory.newQuery( "$out_"+$msgId, $act.getActionName() , $act.getArgsArray()) );
    BatchExecutionCommand batch = CommandFactory.newBatchExecution(list);
    insert( new MessageCommands( $msgId, batch ) );


end


rule "Process_Request_Whenever"
when
    $msg : ACLMessage( $msgId : id, performative == Act.REQUEST_WHENEVER )
    $req : RequestWhenever( $act : action, $actName : action.actionName, $condition : condition.drl ) from $msg.body
    $dst : Destination( $msgId ; )
then
    System.err.println(" INTERNAL PROCESSING : GENERATING COMMANDS FOR REQUEST WHEN " + $msgId + " " + $condition);
    ActionHolder holder = new ActionHolder($msgId, $act, $condition, true);

    insert( new OneShotMessageCommand( $msgId,  CommandFactory.newInsert( holder ) ) );

    java.util.List list = new ArrayList(1);
              list.add(CommandFactory.newFireAllRules());
//            list.add(CommandFactory.newQuery( "$out_"+$msgId, $act.getActionName() , $act.getArgsArray()) );
    BatchExecutionCommand batch = CommandFactory.newBatchExecution(list);
    insert( new MessageCommands( $msgId, batch ) );


end






