/*
    Common declarations for Drools Agents
*/

package org.drools.fipa;

import org.drools.command.Command;
import org.drools.command.BatchExecutionCommand;
import org.drools.runtime.StatefulKnowledgeSession;
import java.util.Map;

import org.drools.base.*;

import org.drools.fipa.body.content.Action;


// ACL message factory, to generate responses
global ACLMessageFactory aclFactory;

// Agent name
global AgentID agentName;

// References to slave sessions
global Map proxies;



// messages are declared events to handle timestamping
declare ACLMessage
    @role(event)
end



// reference between a message and the commands to process that message content in a remote session
declare MessageCommands
    msgId : String
    cmd : Command
end

declare OneShotMessageCommand
    msgId : String
    payload : Command
end

// custom mapping between sessions and domain-specific identifiers (e.g. patient id)
declare SessionMapping
    key : String
    sessionId : String
end

// association between a message and the session where its contents are to be processed
declare Destination
    messageId : String
    sessionId : String
end

declare ResponseContent
    messageId : String
    data : Object
end





