package org.drools.fipa.reduced.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-b02- Generated
 * source version: 2.1
 *
 */
@WebServiceClient(name = "SynchronousDroolsAgentServiceImplService", targetNamespace = "http://drools-fipa-agent.drools.org/", wsdlLocation = "http://localhost:9944/drools-fipa-agent/service/SynchronousDroolsAgentService?wsdl")
public class SynchronousDroolsAgentServiceImplService
        extends Service {

    private final static Logger logger = Logger.getLogger(SynchronousDroolsAgentServiceImplService.class.getName());

    public SynchronousDroolsAgentServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SynchronousDroolsAgentServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, new QName("http://drools-fipa-agent.drools.org/", "SynchronousDroolsAgentServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns SynchronousDroolsAgentServiceImpl
     */
    @WebEndpoint(name = "SynchronousDroolsAgentServiceImplPort")
    public SynchronousDroolsAgentServiceImpl getSynchronousDroolsAgentServiceImplPort() {
        return super.getPort(new QName("http://drools-fipa-agent.drools.org/", "SynchronousDroolsAgentServiceImplPort"), SynchronousDroolsAgentServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SynchronousDroolsAgentServiceImpl
     */
    @WebEndpoint(name = "SynchronousDroolsAgentServiceImplPort")
    public SynchronousDroolsAgentServiceImpl getSynchronousDroolsAgentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://drools-fipa-agent.drools.org/", "SynchronousDroolsAgentServiceImplPort"), SynchronousDroolsAgentServiceImpl.class, features);
    }
}
