
package org.drools.fipa.reduced.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.drools.fipa.ACLMessage;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SynchronousDroolsAgentServiceImpl", targetNamespace = "http://drools-fipa-agent.drools.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SynchronousDroolsAgentServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.drools.fipa.ACLMessage>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tell", targetNamespace = "http://drools-fipa-agent.drools.org/", className = "org.drools.fipa.reduced.client.Tell")
    @ResponseWrapper(localName = "tellResponse", targetNamespace = "http://drools-fipa-agent.drools.org/", className = "org.drools.fipa.reduced.client.TellResponse")
    public List<ACLMessage> tell(
        @WebParam(name = "arg0", targetNamespace = "")
        ACLMessage arg0);

}
